### ISSUE TITLE
New ABI version support in repository

### ISSUE THREAD

**Issue by bbarker** [eugenkiss/kotlinfx#10]
Hello,

It seems that the latest version of kotlinfx is several ABI versions behind kotlin now. A more recent version might be helpful.

Thanks!

**Comment by eugenkiss** [comment]
Hi,

sorry for the late response. I'll investigate today and let you know then.

**Comment by eugenkiss** [comment]
I've updated [KotlinFX to Kotlin M10.1](90f97fd239811230c2025ef3aaa2563b96f40896) and pushed a new 0.2-SNAPSHOT to the Maven repository. I hope that helps!

**Comment by bbarker** [comment]
Thanks much - I finally got around to getting my gradle script working and
was able to build a simple kotlinfx app. Looking forward to trying more
this weekend.

On Mon, Mar 2, 2015 at 1:10 PM, Eugen Kiss <notifications@github.com> wrote:

> I've updated KotlinFX to Kotlin M10.1
> <http://90f97fd239811230c2025ef3aaa2563b96f40896> and pushed a new
> 0.2-SNAPSHOT to the Maven repository. I hope that helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eugenkiss/kotlinfx/issues/10#issuecomment-76765829>.
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by eugenkiss** [comment]
No problem, have fun!
